### ISSUE TITLE
项目的运行方式和数据是否可存储？

### ISSUE THREAD

**Issue by paulfrom** [decaywood/XueQiuSuperSpider#3]
我发现这个项目类似一个框架项目，对于项目的使用（运行，目前好像只有测试用例可直接运行）和部分配置不是很了解，希望能有一个简单的说明，谢谢。

**Comment by decaywood** [comment]
首先需要明确一下，这个项目严格来说是一个库而不是框架。明确这一点后，你可以认为它的目的仅仅是简化你的数据分析工作而已。至于数据的存储，由于用户使用何种数据库并不知道，框死的话不符合拓展原则，但是你可以自行拓展此功能，数据存储在此框架里面应该算是Consumer操作，属于工作流的末尾工作了，继承Consumer接口实现你的数据库逻辑，插入工作流末端即可。整个库暂时只有一些结构性的介绍，库的使用门槛还算有一定要求，并不会提供手把手的教程，因为毕竟是抓取别人的数据，不是固定接口，万一雪球网站变了，库的实现也得跟着变，维护起来太困难了，在此表示抱歉。不过源码里面有较详细的说明，可以配合例子慢慢理解，我可以保证，当你理解整个库的思路以后，使用起来会得心应手，可以拓展出很多实用的功能。在此谢谢关注我的项目，如有不足还请继续指正！
